language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-22
    - extra-android-m2repository

before_script:
    - chmod +x gradlew

script:
    ./gradlew build
